name = "AdaptivePredicates"
uuid = "35492f91-a3bd-45ad-95db-fcad7dcfedb7"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.3"
julia = "1.8"

[workspace]
projects = ["test"]