name = "AdaptivePredicates"
uuid = "35492f91-a3bd-45ad-95db-fcad7dcfedb7"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8"

[workspace]
projects = ["test"]
